datasource:
  - driver: mysql
    username: root
    password: root123
    url: tcp(localhost:3306)/resk?charset=utf8&parseTime=true&loc=Local
    datasourceName: resk

server:
  port: 7000
logger:
  level: debug
  showSql: false
oss:
  accessKey: minioadmin
  secretKey: minioadmin
  endpoint: 127.0.0.1:9000
  bucketName: boden-file
  bucketNameThumbnail: boden-file-thumbnail
