datasource:
  - driver: mysql
    username: root
    password: yyxing
    url: tcp(localhost:3306)/sell?charset=utf8&parseTime=true
    datasourceName: sell
  - driver: mysql
    username: root
    password: root123
    url: tcp(154.8.173.3:33606)/video_server?charset=utf8&parseTime=true
    datasourceName: video_server