datasource:
  - driver: mysql
    username: root
    password: root123
    url: tcp(localhost:3306)/resk?charset=utf8&parseTime=true&loc=Local
    datasourceName: resk

server:
  port: 8000
logger:
  level: debug
  showSql: true
